{% set name = "TileDB" %}
{% set version = "2.26.2" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/TileDB-Inc/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 255218aebd3ef5af4b8deb3be58f877fda335d5abc1c097a33f6741bf259a68d

build:
  number: 4
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=tiledb
    - {{ pin_subpackage('tiledb', max_pin='x.x') }}
  script_env:
    # "Environment variable VCPKG_FORCE_SYSTEM_BINARIES must be set on
    # arm, s390x, ppc64le and riscv platforms."
    - VCPKG_FORCE_SYSTEM_BINARIES=1  # [ arm64 or aarch64 or s390x or ppc64le]

requirements:
  build:
    - ninja-base
    - sed  # [not win]
    - gawk  # [not win]
    - cmake
    - pkg-config  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib {{ zlib }}
    - bzip2 {{ bzip2 }}
    - zstd {{ zstd }}
    - libcurl {{ libcurl }}
    - openssl {{ openssl }}
    - spdlog 1.11.0
    - capnproto 1.1.0
    - libmagic 5.46
    - fmt 9.1
    - lz4-c 1.9
    - aws-sdk-cpp 1.11.528
    - aws-c-common 0.11
    - aws-crt-cpp 0.31
    - azure-core-cpp 1.14
    - azure-identity-cpp 1.10
    - azure-storage-blobs-cpp 12.13
    - libwebp-base {{ libwebp }}

test:
  requires:
    - {{ compiler('cxx') }}  # [unix]
    - cmake                  # [unix]
    - make                   # [unix]
  commands:
    - test -e $PREFIX/include/tiledb/tiledb.h  # [not win]
    - test -e $PREFIX/include/tiledb/tiledb    # [not win]
    - test -e $PREFIX/lib/libtiledb$SHLIB_EXT  # [not win]
    - test -e $PREFIX/lib/pkgconfig/tiledb.pc  # [not win]

    - if exist %LIBRARY_INC%\\tiledb\\tiledb (exit 0) else (exit 1)    # [win]
    - if exist %LIBRARY_INC%\\tiledb\\tiledb.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_LIB%\\tiledb.lib (exit 0) else (exit 1)        # [win]
    - if exist %LIBRARY_BIN%\\tiledb.dll (exit 0) else (exit 1)        # [win]

    - if exist %LIBRARY_LIB%\\cmake\\TileDB\\TileDBConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_LIB%\\pkgconfig\\tiledb.pc (exit 0) else (exit 1)               # [win]

about:
  home: https://tiledb.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: TileDB sparse and dense multi-dimensional array data management
  description: |
    TileDB is an efficient multi-dimensional array management system which introduces
    a novel on-disk format that can effectively store dense and sparse array data with
    support for fast updates and reads. It features excellent compression, and an efficient
    parallel I/O system with high scalability.
  doc_url: https://cloud.tiledb.com/academy/home/
  dev_url: https://github.com/TileDB-Inc/TileDB

extra:
  skip-lints:
    - has_run_test_and_commands
    - invalid_url  # https://cloud.tiledb.com/academy/home/ : Not reachable: 405
  recipe-maintainers:
    - stavrospapadopoulos
    - shelnutt2
    - ihnorton
    - nguyenv
