{% set name = "TileDB" %}
{% set version = "2.30.0" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/TileDB-Inc/{{ name }}/archive/{{ version }}.tar.gz
  sha256: c5f94da6de0e0f93925f7ad107bd80fef0615f9b3d111a5bae245f75b1fcc173

build:
  number: 0
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=tiledb
    - {{ pin_subpackage('tiledb', max_pin='x.x') }}

requirements:
  build:
    - ninja-base
    - git  # [win]
    - sed  # [not win]
    - gawk  # [not win]
    - cmake
    - pkg-config  # [not win]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib {{ zlib }}
    - bzip2 {{ bzip2 }}
    - zstd {{ zstd }}
    - libcurl {{ libcurl }}
    - openssl {{ openssl }}
    - spdlog {{ spdlog }}
    - capnproto {{ capnproto }}
    - libmagic 5.46
    - fmt {{ fmt }}
    - c-blosc2 {{ c_blosc2 }}
    - lz4-c {{ lz4_c }}
    - aws-sdk-cpp {{ aws_sdk_cpp }}
    - aws-c-common {{ aws_c_common }}
    - aws-crt-cpp {{ aws_crt_cpp }}
    - azure-core-cpp {{ azure_core_cpp }}
    - azure-identity-cpp {{ azure_identity_cpp }}
    - azure-storage-common-cpp {{ azure_storage_common_cpp }}
    - azure-storage-blobs-cpp {{ azure_storage_blobs_cpp }}
    - azure-storage-files-datalake-cpp {{ azure_storage_files_datalake_cpp }}
    - libwebp-base {{ libwebp }}
    - nlohmann_json 3.11.2 # [win]

test:
  requires:
    - {{ compiler('cxx') }}  # [unix]
    - cmake                  # [unix]
    - make                   # [unix]
  commands:
    - test -e $PREFIX/include/tiledb/tiledb.h  # [not win]
    - test -e $PREFIX/include/tiledb/tiledb    # [not win]
    - test -e $PREFIX/lib/libtiledb$SHLIB_EXT  # [not win]
    - test -e $PREFIX/lib/pkgconfig/tiledb.pc  # [not win]

    - if exist %LIBRARY_INC%\\tiledb\\tiledb (exit 0) else (exit 1)    # [win]
    - if exist %LIBRARY_INC%\\tiledb\\tiledb.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_LIB%\\tiledb.lib (exit 0) else (exit 1)        # [win]
    - if exist %LIBRARY_BIN%\\tiledb.dll (exit 0) else (exit 1)        # [win]

    - if exist %LIBRARY_LIB%\\cmake\\TileDB\\TileDBConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_LIB%\\pkgconfig\\tiledb.pc (exit 0) else (exit 1)               # [win]

about:
  home: https://tiledb.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: TileDB sparse and dense multi-dimensional array data management
  description: |
    TileDB is an efficient multi-dimensional array management system which introduces
    a novel on-disk format that can effectively store dense and sparse array data with
    support for fast updates and reads. It features excellent compression, and an efficient
    parallel I/O system with high scalability.
  doc_url: https://cloud.tiledb.com/academy/home
  dev_url: https://github.com/TileDB-Inc/TileDB

extra:
  skip-lints:
    - has_run_test_and_commands
    - invalid_url  # https://cloud.tiledb.com/academy/home/ : Not reachable: 405
  recipe-maintainers:
    - stavrospapadopoulos
    - shelnutt2
    - ihnorton
    - nguyenv
